### ISSUE TITLE
Inform ENOENT

### ISSUE THREAD

**Issue by pronebird** [hsk81/protobuf-rpc-js#3]
Hey,

Great example!

However, web server does not seem to work:
[404] /inform: Error: ENOENT: no such file or directory, stat '/root/rpc.git/example/client/js-www/inform'

some file is missing in repo?

**Comment by notexeditor** [comment]
@pronebird: there are multiple web servers; which one are you talking about? please provide fix as a pull request.

**Comment by pronebird** [comment]
it's js-www. I am not sure where this inform comes from. Looks like missing file to me..

**Comment by notexeditor** [comment]
@pronebird Use:
```
$ ./example/client/js-www/index.js 
```
```
Paper Server - listening on http://localhost:8080/
```
Then open `http://localhost:8080/` in your browser, hit `F12` (for Chrome) and verify in the inspector console:
```
(index):70 [on:add] e {lhs: 2, rhs: 3} e {value: 5} null
(index):77 [on:sub] e {lhs: 2, rhs: 3} e {value: -1} null
(index):84 [on:mul] e {lhs: 2, rhs: 3} e {value: 6} null
(index):91 [on:div] e {lhs: 2, rhs: 3} e {value: 0} null
```
```
(index):61 [on:ack] e {timestamp: "2018-05-28T22:07:59.307Z"} e {timestamp: "2018-05-28T22:07:59.307Z"} null
```
