### ISSUE TITLE
Does not work with latest protobufjs

### ISSUE THREAD

**Issue by pronebird** [hsk81/protobuf-rpc-js#4]

**Comment by notexeditor** [comment]
@pronebird: Thanks for the feedback: please describe detailed nature of error, and better provide a *pull request* fixing the issue.

**Comment by notexeditor** [comment]
@pronebird Upgraded to `"protobufjs": "^6.8.6"`.

**Comment by pronebird** [comment]
@hsk81 thanks! It's been few years but I am glad it's solved 💃
